/*
 * Copyright (C) Techfaith 2002-2005.
 * All rights reserved.
 *
 * This software is covered by the license agreement between
 * the end user and Techfaith, and may be 
 * used and copied only in accordance with the terms of the 
 * said agreement.
 *
 * Techfaith assumes no responsibility or 
 * liability for any errors or inaccuracies in this software, 
 * or any consequential, incidental or indirect damage arising
 * out of the use of the software.
 *
 */
/*
 *
 *
 * We_Mime.c
 *
 * File extension to MIME type conversion.
 *
 */

#include "We_Cmmn.h"
#include "We_Mime.h"
#include "We_Xmim.h"
#include "We_Lib.h"

#define WE_MIME_DEFAULT_MIME "application/x-techfaith-unknown-mime"

/************************************************************
 * Hash table generated by mkhash.pl
 ************************************************************/
static const unsigned char we_mime_ext_hash_table[] = {
  2, 255, 255, 255, 255, 21, 46, 20, 7, 255,
  0, 37, 28, 43, 29, 19, 6, 41, 255, 255,
  11, 36, 15, 255, 34, 38, 3, 255, 40, 23,
  27, 255, 255, 5, 12, 45, 255, 9, 8, 255,
  30, 255, 47, 255, 255, 18, 255, 255, 39, 1,
  255, 42, 255, 14, 22, 255, 31, 255, 4, 24,
  16, 44, 255, 17, 33, 255, 13, 10, 35, 26,
  25, 32, 255
};

#define WE_EXT_HASH_TABLE_SIZE                 73
#define WE_EXT_STRING_TABLE_SIZE               48

static const we_strtable_entry_t we_mime_ext_strings[] = {
  "class",    WE_MIME_TYPE_APPLICATION_JAVA_VM,
  "cer",      WE_MIME_TYPE_APPLICATION_X_X509_CA_CERT,
  "usr",      WE_MIME_TYPE_APPLICATION_X_X509_USER_CERT,
  "mid",      WE_MIME_TYPE_AUDIO_MID,
  "midi",     WE_MIME_TYPE_AUDIO_MID,
  "mp3",      WE_MIME_TYPE_AUDIO_MPEG,
  "wav",      WE_MIME_TYPE_AUDIO_X_WAV,
  "gif",      WE_MIME_TYPE_IMAGE_GIF,
  "jpg",      WE_MIME_TYPE_IMAGE_JPEG,
  "jpe",      WE_MIME_TYPE_IMAGE_JPEG,
  "jpeg",     WE_MIME_TYPE_IMAGE_JPEG,
  "png",      WE_MIME_TYPE_IMAGE_PNG,
  "tif",      WE_MIME_TYPE_IMAGE_TIFF,
  "tiff",     WE_MIME_TYPE_IMAGE_TIFF,
  "css",      WE_MIME_TYPE_TEXT_CSS,
  "html",     WE_MIME_TYPE_TEXT_HTML,
  "htm",      WE_MIME_TYPE_TEXT_HTML,
  "asc",      WE_MIME_TYPE_TEXT_PLAIN,
  "tex",      WE_MIME_TYPE_TEXT_PLAIN,
  "text",     WE_MIME_TYPE_TEXT_PLAIN,
  "txt",      WE_MIME_TYPE_TEXT_PLAIN,
  "xml",      WE_MIME_TYPE_TEXT_XML,
  "vcf",      WE_MIME_TYPE_TEXT_X_VCARD,
  "dm",       WE_MIME_TYPE_APPLICATION_VND_OMA_DRM_MESSAGE,
  "drm",      WE_MIME_TYPE_APPLICATION_VND_OMA_DRM_MESSAGE,
  "dcf",      WE_MIME_TYPE_APPLICATION_VND_OMA_DRM_CONTENT,
  "wbmp",     WE_MIME_TYPE_IMAGE_VND_WAP_WBMP,
  "wbm",      WE_MIME_TYPE_IMAGE_VND_WAP_WBMP,
  "smi",      WE_MIME_TYPE_APPLICATION_SMIL,
  "wml",      WE_MIME_TYPE_TEXT_VND_WAP_WML,
  "wmlc",     WE_MIME_TYPE_APPLICATION_VND_WAP_WMLC,
  "wmls",     WE_MIME_TYPE_TEXT_VND_WAP_WMLSCRIPT,
  "wmlsc",    WE_MIME_TYPE_APPLICATION_VND_WAP_WMLSCRIPTC,
  "wpng",     WE_MIME_TYPE_IMAGE_X_UP_WPNG,
  "vcs",      WE_MIME_TYPE_TEXT_X_VCALENDAR,
  "svg",      WE_MIME_TYPE_IMAGE_SVG,
  "bmp",      WE_MIME_TYPE_IMAGE_BMP,
  "mpg",      WE_MIME_TYPE_VIDEO_MPEG,
  "mpeg",     WE_MIME_TYPE_VIDEO_MPEG,
  "mpe",      WE_MIME_TYPE_VIDEO_MPEG,
  "mmf",      WE_MIME_TYPE_APPLICATION_VND_SIAF,
  "mmf",      WE_MIME_TYPE_APPLICATION_X_SIAF, 
  "amr",      WE_MIME_TYPE_AUDIO_AMR,
  "swf",      WE_MIME_TYPE_APPLICATION_X_SHOCKWAVE_FLASH,
  "zip",      WE_MIME_TYPE_APPLICATION_ZIP,
  "imy",      WE_MIME_TYPE_AUDIO_IMELODY,
  "3gp",      WE_MIME_TYPE_VIDEO_3GPP,  /* Video support*/
  "mp4",      WE_MIME_TYPE_VIDEO_MP4,   /* Video support*/
};


/************************************************************
 * Hash table etc. for MIME types generated by mkhash.pl
 ************************************************************/
static const unsigned char we_mime_type_hash_table[] = {
  84, 53, 255, 64, 3, 255, 60, 116, 97, 255,
  44, 255, 47, 255, 5, 79, 32, 30, 255, 75,
  59, 255, 80, 29, 255, 255, 255, 255, 255, 39,
  43, 1, 68, 255, 114, 66, 34, 255, 255, 102,
  255, 22, 90, 255, 255, 255, 255, 255, 15, 54,
  94, 72, 96, 14, 82, 71, 55, 0, 255, 108,
  13, 26, 33, 255, 89, 255, 48, 37, 17, 51,
  105, 36, 2, 87, 255, 255, 101, 58, 86, 88,
  255, 21, 117, 45, 255, 99, 255, 100, 74, 111,
  255, 98, 28, 255, 41, 255, 27, 83, 255, 7,
  255, 63, 10, 255, 50, 255, 76, 9, 255, 107,
  52, 255, 81, 77, 104, 69, 19, 4, 95, 255,
  56, 113, 42, 31, 78, 255, 25, 85, 255, 49,
  93, 73, 91, 18, 255, 46, 12, 103, 109, 110,
  8, 255, 255, 6, 255, 62, 67, 255, 23, 20,
  255, 255, 65, 255, 70, 61, 255, 112, 255, 255,
  255, 255, 11, 255, 38, 24, 40, 255, 255, 115,
  92, 16, 35, 118, 57, 255, 255, 255, 106
};

#define WE_MIME_TYPE_HASH_TABLE_SIZE                 179
#define WE_MIME_TYPE_STRING_TABLE_SIZE               119

static const we_strtable_entry_t we_mime_type_strings[] = {
  {"*/*", WE_MIME_TYPE_ANY_ANY},
  {"text/*", WE_MIME_TYPE_TEXT_ANY},
  {"text/html", WE_MIME_TYPE_TEXT_HTML},
  {"text/plain", WE_MIME_TYPE_TEXT_PLAIN},
  {"text/x-hdml", WE_MIME_TYPE_TEXT_X_HDML},
  {"text/x-ttml", WE_MIME_TYPE_TEXT_X_TTML},
  {"text/x-vcalendar", WE_MIME_TYPE_TEXT_X_VCALENDAR},
  {"text/x-vcard", WE_MIME_TYPE_TEXT_X_VCARD},
  {"text/vnd.wap.wml", WE_MIME_TYPE_TEXT_VND_WAP_WML},
  {"text/vnd.wap.wmlscript", WE_MIME_TYPE_TEXT_VND_WAP_WMLSCRIPT},
  {"text/vnd.wap.channel", WE_MIME_TYPE_TEXT_VND_WAP_CHANNEL},
  {"multipart/*", WE_MIME_TYPE_MULTIPART_ANY},
  {"multipart/mixed", WE_MIME_TYPE_MULTIPART_MIXED},
  {"multipart/form-data", WE_MIME_TYPE_MULTIPART_FORM_DATA},
  {"multipart/byteranges", WE_MIME_TYPE_MULTIPART_BYTERANGES},
  {"multipart/alternative", WE_MIME_TYPE_MULTIPART_ALTERNATIVE},
  {"application/*", WE_MIME_TYPE_APPLICATION_ANY},
  {"application/java-vm", WE_MIME_TYPE_APPLICATION_JAVA_VM},
  {"application/x-www-form-urlencoded", WE_MIME_TYPE_APPLICATION_X_WWW_FORM_URLENCODED},   
  {"application/x-hdmlc", WE_MIME_TYPE_APPLICATION_X_HDMLC},
  {"application/vnd.wap.wmlc", WE_MIME_TYPE_APPLICATION_VND_WAP_WMLC},
  {"application/vnd.wap.wmlscriptc", WE_MIME_TYPE_APPLICATION_VND_WAP_WMLSCRIPTC},   
  {"application/vnd.wap.channelc", WE_MIME_TYPE_APPLICATION_VND_WAP_CHANNELC},
  {"application/vnd.wap.uaprof", WE_MIME_TYPE_APPLICATION_VND_WAP_UAPROF},
  {"application/vnd.wap.wtls-ca-certificate", WE_MIME_TYPE_APPLICATION_VND_WAP_WTLS_CA_CERTIFICATE},   
  {"application/vnd.wap.wtls-user-certificate", WE_MIME_TYPE_APPLICATION_VND_WAP_WTLS_USER_CERTIFICATE},   
  {"application/x-x509-ca-cert", WE_MIME_TYPE_APPLICATION_X_X509_CA_CERT},
  {"application/x-x509-user-cert", WE_MIME_TYPE_APPLICATION_X_X509_USER_CERT},
  {"image/*", WE_MIME_TYPE_IMAGE_ANY},
  {"image/gif", WE_MIME_TYPE_IMAGE_GIF},
  {"image/jpeg", WE_MIME_TYPE_IMAGE_JPEG},
  {"image/tiff", WE_MIME_TYPE_IMAGE_TIFF},
  {"image/png", WE_MIME_TYPE_IMAGE_PNG},
  {"image/vnd.wap.wbmp", WE_MIME_TYPE_IMAGE_VND_WAP_WBMP},
  {"application/vnd.wap.multipart.*", WE_MIME_TYPE_APPLICATION_VND_WAP_MULTIPART_ANY},   
  {"application/vnd.wap.multipart.mixed", WE_MIME_TYPE_APPLICATION_VND_WAP_MULTIPART_MIXED},   
  {"application/vnd.wap.multipart.form-data", WE_MIME_TYPE_APPLICATION_VND_WAP_MULTIPART_FORM_DATA},   
  {"application/vnd.wap.multipart.byteranges", WE_MIME_TYPE_APPLICATION_VND_WAP_MULTIPART_BYTERANGES},   
  {"application/vnd.wap.multipart.alternative", WE_MIME_TYPE_APPLICATION_VND_WAP_MULTIPART_ALTERNATIVE},   
  {"application/xml", WE_MIME_TYPE_APPLICATION_XML},
  {"text/xml", WE_MIME_TYPE_TEXT_XML},
  {"application/vnd.wap.wbxml", WE_MIME_TYPE_APPLICATION_VND_WAP_WBXML},
  {"application/x-x968-cross-cert", WE_MIME_TYPE_APPLICATION_X_X968_CROSS_CERT},   
  {"application/x-x968-ca-cert", WE_MIME_TYPE_APPLICATION_X_X968_CA_CERT},
  {"application/x-x968-user-cert", WE_MIME_TYPE_APPLICATION_X_X968_USER_CERT},
  {"text/vnd.wap.si", WE_MIME_TYPE_TEXT_VND_WAP_SI},
  {"application/vnd.wap.sic", WE_MIME_TYPE_APPLICATION_VND_WAP_SIC},
  {"text/vnd.wap.sl", WE_MIME_TYPE_TEXT_VND_WAP_SL},
  {"application/vnd.wap.slc", WE_MIME_TYPE_APPLICATION_VND_WAP_SLC},
  {"text/vnd.wap.co", WE_MIME_TYPE_TEXT_VND_WAP_CO},
  {"application/vnd.wap.coc", WE_MIME_TYPE_APPLICATION_VND_WAP_COC},
  {"application/vnd.wap.multipart.related", WE_MIME_TYPE_APPLICATION_VND_WAP_MULTIPART_RELATED},  
  {"application/vnd.wap.sia", WE_MIME_TYPE_APPLICATION_VND_WAP_SIA},
  {"text/vnd.wap.connectivity-xml", WE_MIME_TYPE_TEXT_VND_WAP_CONNECTIVITY_XML},   
  {"application/vnd.wap.connectivity-wbxml", WE_MIME_TYPE_APPLICATION_VND_WAP_CONNECTIVITY_WBXML},
  {"application/pkcs7-mime", WE_MIME_TYPE_APPLICATION_PKCS7_MIME},
  {"application/vnd.wap.hashed-certificate", WE_MIME_TYPE_APPLICATION_VND_WAP_HASHED_CERTIFICATE},
  {"application/vnd.wap.signed-certificate", WE_MIME_TYPE_APPLICATION_VND_WAP_SIGNED_CERTIFICATE},
  {"application/vnd.wap.cert-response", WE_MIME_TYPE_APPLICATION_VND_WAP_CERT_RESPONSE},
  {"application/xhtml+xml", WE_MIME_TYPE_APPLICATION_XHTML_XML},
  {"application/wml+xml", WE_MIME_TYPE_APPLICATION_WML_XML},
  {"text/css", WE_MIME_TYPE_TEXT_CSS},
  {"application/vnd.wap.mms-message", WE_MIME_TYPE_APPLICATION_VND_WAP_MMS_MESSAGE},
  {"application/vnd.wap.rollover-certificate", WE_MIME_TYPE_APPLICATION_VND_WAP_ROLLOVER_CERTIFICATE},
  {"application/vnd.wap.locc+wbxml", WE_MIME_TYPE_APPLICATION_VND_WAP_LOCC_WBXML},
  {"application/vnd.wap.loc+xml", WE_MIME_TYPE_APPLICATION_VND_WAP_LOC_XML},
  {"application/vnd.syncml.dm+wbxml", WE_MIME_TYPE_APPLICATION_VND_SYNCML_DM_WBXML},
  {"application/vnd.syncml.dm+xml", WE_MIME_TYPE_APPLICATION_VND_SYNCML_DM_XML},
  {"application/vnd.syncml.notification", WE_MIME_TYPE_APPLICATION_VND_SYNCML_NOTIFICATION},
  {"application/vnd.wap.xhtml+xml", WE_MIME_TYPE_APPLICATION_VND_WAP_XHTML_XML},
  {"application/vnd.wv.csp.cir", WE_MIME_TYPE_APPLICATION_VND_WV_CSP_CIR},
  {"application/vnd.oma.dd+xml", WE_MIME_TYPE_APPLICATION_VND_OMA_DD_XML},
  {"application/vnd.oma.drm.message", WE_MIME_TYPE_APPLICATION_VND_OMA_DRM_MESSAGE},
  {"application/vnd.oma.drm.content", WE_MIME_TYPE_APPLICATION_VND_OMA_DRM_CONTENT},
  {"application/vnd.oma.drm.rights+xml", WE_MIME_TYPE_APPLICATION_VND_OMA_DRM_RIGHTS_XML},
  {"application/vnd.oma.drm.rights+wbxml", WE_MIME_TYPE_APPLICATION_VND_OMA_DRM_RIGHTS_WBXML},
  {"application/vnd.wv.csp+xml", WE_MIME_TYPE_APPLICATION_VND_WV_CSP_XML},
  {"application/vnd.wv.csp+wbxml", WE_MIME_TYPE_APPLICATION_VND_WV_CSP_WBXML},
  {"audio/*", WE_MIME_TYPE_AUDIO_ANY},
  {"audio/mid", WE_MIME_TYPE_AUDIO_MID},
  {"audio/mpeg", WE_MIME_TYPE_AUDIO_MPEG},
  {"audio/x-wav", WE_MIME_TYPE_AUDIO_X_WAV},
  {"application/x-vnd.mms-template-texts", WE_MIME_TYPE_APPLICATION_X_VND_MMS_TEMPLATE_TEXTS},
  {"application/x-wap-prov.browser-settings", WE_MIME_TYPE_APPLICATION_X_WAP_PROV_BROWSER_SETTINGS},
  {"application/x-wap-prov.browser-bookmarks", WE_MIME_TYPE_APPLICATION_X_WAP_PROV_BROWSER_BOOKMARKS},
  {"application/x-prov.syncset+xml", WE_MIME_TYPE_APPLICATION_X_WAP_PROV_SYNCSET_XML},
  {"application/x-prov.syncset+wbxml", WE_MIME_TYPE_APPLICATION_X_WAP_PROV_SYNCSET_WBXML},  
  {"application/smil", WE_MIME_TYPE_APPLICATION_SMIL},
  {"image/svg+xml", WE_MIME_TYPE_IMAGE_SVG},
  {"image/bmp", WE_MIME_TYPE_IMAGE_BMP},
  {"video/mpeg", WE_MIME_TYPE_VIDEO_MPEG},
  {"application/vnd.siaf", WE_MIME_TYPE_APPLICATION_VND_SIAF},
  {"application/x-siaf", WE_MIME_TYPE_APPLICATION_X_SIAF},
  {"audio/amr", WE_MIME_TYPE_AUDIO_AMR},
  {"application/x-shockwave-flash", WE_MIME_TYPE_APPLICATION_X_SHOCKWAVE_FLASH},
  {"application/zip", WE_MIME_TYPE_APPLICATION_ZIP},
  {"audio/midi", WE_MIME_TYPE_AUDIO_MID},
  {"audio/x-midi", WE_MIME_TYPE_AUDIO_X_MIDI},
  {"audio/sp-midi", WE_MIME_TYPE_AUDIO_SP_MIDI},
  {"application/vnd.uplanet.cacheop-wbxml", WE_MIME_TYPE_APPLICATION_VND_UPLANET_CACHEOP_WBXML},
  {"application/vnd.uplanet.signal", WE_MIME_TYPE_APPLICATION_VND_UPLANET_SIGNAL},
  {"application/vnd.uplanet.alert-wbxml", WE_MIME_TYPE_APPLICATION_VND_UPLANET_ALERT_WBXML},
  {"application/vnd.uplanet.list-wbxml", WE_MIME_TYPE_APPLICATION_VND_UPLANET_LIST_WBXML},
  {"application/vnd.uplanet.listcmd-wbxml", WE_MIME_TYPE_APPLICATION_VND_UPLANET_LISTCMD_WBXML},
  {"application/vnd.uplanet.channel-wbxml", WE_MIME_TYPE_APPLICATION_VND_UPLANET_CHANNEL_WBXML},
  {"application/vnd.uplanet.provisioning-status-uri", WE_MIME_TYPE_APPLICATION_VND_UPLANET_PROVISIONING_STATUS_URI},
  {"x-wap.multipart/vnd.uplanet.header-set", WE_MIME_TYPE_X_WAP_MULTIPART_VND_UPLANET_HEADER_SET},
  {"application/vnd.uplanet.bearer-choice-wbxml", WE_MIME_TYPE_APPLICATION_VND_UPLANET_BEARER_CHOICE_WBXML},
  {"application/vnd.phonecom.mmc-wbxml", WE_MIME_TYPE_APPLICATION_VND_PHONECOM_MMC_WBXML},
  {"application/vnd.nokia.syncset+wbxml", WE_MIME_TYPE_APPLICATION_VND_NOKIA_SYNCSET_WBXML},
  {"image/x-up-wpng", WE_MIME_TYPE_IMAGE_X_UP_WPNG},
  {"application/iota.mmc-wbxml", WE_MIME_TYPE_APPLICATION_IOTA_MMC_WBXML},
  {"application/iota.mmc-xml", WE_MIME_TYPE_APPLICATION_IOTA_MMC},
  {"audio/imelody", WE_MIME_TYPE_AUDIO_IMELODY},
  {"text/x-imelody", WE_MIME_TYPE_TEXT_X_IMELODY},
  {"video/3gpp", WE_MIME_TYPE_VIDEO_3GPP},  /* Video support*/             
  {"audio/3gpp", WE_MIME_TYPE_AUDIO_3GPP},  /* Video support*/
  {"video/mp4", WE_MIME_TYPE_VIDEO_MP4 },   /* Video support*/            
  {"audio/mp4", WE_MIME_TYPE_AUDIO_MP4 },   /* Video support*/
};


const we_strtable_info_t we_mime_types = {
  we_mime_type_hash_table,
  WE_MIME_TYPE_HASH_TABLE_SIZE,
  WE_TABLE_SEARCH_LINEAR,
  we_mime_type_strings,
  WE_MIME_TYPE_STRING_TABLE_SIZE
};

const we_strtable_info_t we_mime_extensions = {
  we_mime_ext_hash_table,
  WE_EXT_HASH_TABLE_SIZE,
  WE_TABLE_SEARCH_LINEAR,
  we_mime_ext_strings,
  WE_EXT_STRING_TABLE_SIZE
};


const char *
we_mime_ext_to_mime (const char *ext)
{
  const char *s;
  int         i;

  if (ext == NULL) {
    return WE_MIME_DEFAULT_MIME;
  }

  i = we_cmmn_str2int_lc (ext, strlen (ext), &we_mime_extensions);

  if (i >= 0) {
    s = we_cmmn_int2str (i, &we_mime_types);
    if (s != NULL) {
      return s;
    }
  }

  /*
   * If there were no match in the predefined mime string table try
   * additional mime type table
   */

#if WE_NUMBER_OF_ADDITIONAL_MIME_TYPES > 0

  for (i = 0;i < WE_NUMBER_OF_ADDITIONAL_MIME_TYPES; i++) {
    if (we_cmmn_strcmp_nc (we_xmim_table[i].extension, ext) == 0) {
      return we_xmim_table[i].mime;
    }
  }
#endif

  return WE_MIME_DEFAULT_MIME;
}


const char *
we_mime_to_ext (const char *mime)
{
  const char *s;
  int         i;
  
  if (mime == NULL) {
    return NULL;
  }

  i = we_cmmn_str2int_lc (mime, strlen (mime), &we_mime_types);

  if (i >= 0) {
    s = we_cmmn_int2str (i, &we_mime_extensions);
    if (s != NULL) {
      return s;
    }
  }

  /*
   * If there were no match in the predefined mime string table try 
   * additional mime type table
   */
#if WE_NUMBER_OF_ADDITIONAL_MIME_TYPES > 0

  for (i = 0;i < WE_NUMBER_OF_ADDITIONAL_MIME_TYPES; i++) {
    if (we_cmmn_strcmp_nc (we_xmim_table[i].mime, mime) == 0) {
      return we_xmim_table[i].extension;
    }
  }
#endif

  return NULL;
}


WE_INT32 
we_mime_to_int (const char *mime)
{
  int i;

  if (mime == NULL) {
    return -1;
  }

  i = we_cmmn_str2int_lc (mime, strlen (mime), &we_mime_types);

  if (i >= 0) {
    return i;
  }

  /*
   * If there were no match in the predefined mime string table try 
   * additional mime type table
   */
#if WE_NUMBER_OF_ADDITIONAL_MIME_TYPES > 0

  for (i = 0;i < WE_NUMBER_OF_ADDITIONAL_MIME_TYPES; i++) {
    if (we_cmmn_strcmp_nc (we_xmim_table[i].mime, mime) == 0) {
      return we_xmim_table[i].value;
    }
  }
#endif

  return -1;
}


const char *
we_int_to_mime (WE_INT32 known_value)
{
  const char *mime_type;

  mime_type = we_cmmn_int2str (known_value, &we_mime_types);
  if (mime_type != NULL) {
    return mime_type;
  }

  /*
   * If there were no match in the predefined mime string table try 
   * additional mime type table
   */
#if WE_NUMBER_OF_ADDITIONAL_MIME_TYPES > 0
  {
    int i;

    for (i = 0;i < WE_NUMBER_OF_ADDITIONAL_MIME_TYPES; i++) {
      if (we_xmim_table[i].value == known_value) {
        return we_xmim_table[i].mime;
      }
    }
  }
#endif

  return NULL;
}

WE_INT32 
we_mime_ext_to_int (const char *ext)
{
  int i;

  if (ext == NULL) {
    return -1;
  }

  i = we_cmmn_str2int_lc (ext, strlen (ext), &we_mime_extensions);
  if (i >= 0) {
    return i;
  }

  /*
   * If there were no match in the predefined mime string table try 
   * additional mime type table
   */
#if WE_NUMBER_OF_ADDITIONAL_MIME_TYPES > 0

  for (i = 0;i < WE_NUMBER_OF_ADDITIONAL_MIME_TYPES; i++) {
    if (we_cmmn_strcmp_nc (we_xmim_table[i].extension, ext) == 0) {
      return we_xmim_table[i].value;
    }
  }
#endif

  return -1;
}

